baseURL = "http://example.org/"
languageCode = "en-us"
title = "Jitin Sharma"
theme = "hyde-hyde"
disqusShortname = "jitin_sharma"

[params]
    author = "Jitin Sharma"
    title = "Something with software"
    authorimage = "/author.jpg"

    highlightjs = true
    highlightjsstyle = "github"
    postNavigation = false

[params.social]
  	twitter = "_jitinsharma"
  	github = "jitinsharma"
    instagram = "_jitinsharma"
    stackoverflow = "jitinsharma"

[[menu.main]]
    name = "Posts"
    weight = 100
    identifier = "posts"
    url = "/posts/"
[[menu.main]]
    name = "About"
    identifier = "about"
    weight = 200
    url = "/about/"